# This tells Pytest: "The settings below belong to Pytest."
[pytest]  

# This tells Pytest: "Look inside the tests folder when searching for tests."
testpaths = tests 

# This tells Pytest: "Use the following command line options when running tests."
 # --tb=long, short, line, native, no
addopts =
    -v
    -s
 #   --tb=short 
 #   --headed
 #   -n 3
 #   -m "not test"
     

markers =
    sanity: Sanity tests
    smoke: Critical smoke tests
    regression: Full regression tests
    ui: UI automation tests
    api: API automation tests
    negative: Negative scenarios
    conf: Configuration tests
    test: For testing purposes
    valid: Valid scenarios
    json: JSON data tests
    login: Login functionality tests
    dynamic: Dynamic data tests using Faker and UUID
    hooktest: Tests to check hook failure handling
    debug: Debugging tests
    api: API tests
    hybrid: Hybrid tests combining API and UI  